from typing import Any

class Boolean(int): ...
class Int16(int): ...
class UInt16(int): ...
class Int32(int): ...
class UInt32(int): ...
class Int64(int): ...
class UInt64(int): ...
class Byte(int): ...
class Double(float): ...

class _BusObject:
    def GetValue(self, *args: Any, **kwargs: Any) -> Any: ...
    def SetValue(self, *args: Any, **kwargs: Any) -> Any: ...

class SystemBus:
    def get_object(self, service: str, path: str, introspect: bool = True) -> _BusObject: ...
    def list_names(self) -> list[str]: ...
